### ISSUE TITLE
Drop the master?

### ISSUE THREAD

**Issue by abitrolly** [theghostbel/capture-asteroid#10]
@theghostbel what if we will just push everything to gh-pages?

**Comment by theghostbel** [comment]
we can create extra page with README.md file content, is it what you mean?

**Comment by abitrolly** [comment]
No, I mean that I need to push both to master and to gh-pages and that's doesn't make sense, because content is the same. We don't need master at all.

**Comment by theghostbel** [comment]
you can push only to master and then update gh-pages with single command `git push -f origin master:gh-pages`
But I don't mind of removing master branch and using gh-pages. Feel free to udpate

**Comment by abitrolly** [comment]
@theghostbel you need to select `gh-pages` as a default branch in repository settings so that I can drop it here - https://github.com/theghostbel/capture-asteroid/branches

**Comment by theghostbel** [comment]
@abitrolly Done, gh-pages is a default branch
