### ISSUE TITLE
humans.txt

### ISSUE THREAD

**Issue by abitrolly** [theghostbel/capture-asteroid#12]
Get a list of all people contributed, specifically mention very specific tasks like application programming and grasshopper expertise (good for resume and asking questions later).

Get list of all people who were involved in video works, from advice to actual support. This is a good practice (and I'd say vital or even critical) to get money free process going.

**Comment by theghostbel** [comment]
Added https://github.com/theghostbel/capture-asteroid/blob/master/CONTRIBUTORS.md, feel free to update file
